/** @type {import('tailwindcss').Config} */

const defaultTheme = require('tailwindcss/defaultTheme');

module.exports = {
  darkMode: 'class',
  content: ['src/pages/**/*.tsx', 'src/components/**/*.tsx'],
  theme: {
    screens: {
      xs: '300px', // Mobile (iPhone 3 - iPhone XS Max).
      userCardsXS: '390px', // 390 pixels for card sizing
      sm: '576px', // Mobile (matches max: iPhone 11 Pro Max landscape @ 896px).
      md: '898px', // Tablet (matches max: iPad Pro @ 1112px).
      lg: '1200px', // Desktop smallest.
      xl: '1259px', // Desktop wide.
      '2xl': '1359px', // Desktop widescreen.
      '3xl': '1582px',
      ...defaultTheme.screens
    },
    fontWeight: {
      semibold: '500',
      black: '700'
    },
    extend: {
      screens: {
        xs: '279px' // Mobile (iPhone 3 - iPhone XS Max).
      },
      // prettier-ignore
      colors: {
        'main-purple': '#6E00FF',
        'main-gray': '#E7E9EA',
        'main-grey-text-light' : '#979797',
        'main-gray-text': '#71767B',
        'main-background': '#070707',
        'main-bar': "#121212",
        'main-primary': 'rgb(var(--main-primary) / <alpha-value>)',
        'main-secondary': 'rgb(var(--main-secondary) / <alpha-value>)',
        // 'main-background': 'rgb(var(--main-background) / <alpha-value>)',
        'main-search-background': 'rgb(var(--main-search-background) / <alpha-value>)',
        'main-sidebar-background': 'rgb(var(--main-sidebar-background) / <alpha-value>)',
        'main-accent': 'rgb(var(--main-accent) / <alpha-value>)',
        'accent-yellow': 'rgb(var(--accent-yellow) / <alpha-value>)',
        'accent-blue': 'rgb(var(--accent-blue) / <alpha-value>)',
        'accent-pink': 'rgb(var(--accent-pink) / <alpha-value>)',
        'accent-purple': 'rgb(var(--accent-purple) / <alpha-value>)',
        'accent-orange': 'rgb(var(--accent-orange) / <alpha-value>)',
        'accent-green': 'rgb(var(--accent-green) / <alpha-value>)',
        'accent-red': '#F4212E',
        'dark-primary': '#E7E9EA',
        'dark-secondary': '#71767B',
        'light-primary': '#0F1419',
        'light-secondary': '#536471',
        'dark-border': '#2F3336',
        'light-border': '#EFF3F4',
        'dark-line-reply': '#333639',
        'light-line-reply': '#CFD9DE',
        'twitter-icon': '#D6D9DB',
        'image-preview-hover': '#272C30',
        'main-red': '#E75858',
      "backgroundsdark-100": "var(--backgroundsdark-100)",
      "backgroundsdark-200": "var(--backgroundsdark-200)",
      "backgroundsdark-300": "var(--backgroundsdark-300)",
      "backgroundsdark-50": "var(--backgroundsdark-50)",
      "backgroundslight-100": "var(--backgroundslight-100)",
      "backgroundslight-200": "var(--backgroundslight-200)",
      "backgroundslight-300": "var(--backgroundslight-300)",
      "backgroundslight-dark": "var(--backgroundslight-dark)",
      "basic-alfa11": "var(--basic-alfa11)",
      "basic-alfa12": "var(--basic-alfa12)",
      "basic-alfa14": "var(--basic-alfa14)",
      "basic-alfa15": "var(--basic-alfa15)",
      "basic-alfa16": "var(--basic-alfa16)",
      "basic-alfa24": "var(--basic-alfa24)",
      "basic-alfa32": "var(--basic-alfa32)",
      "basic-alfa48": "var(--basic-alfa48)",
      "basic-alfa5": "var(--basic-alfa5)",
      "basic-alfa7": "var(--basic-alfa7)",
      "basic-alfa8": "var(--basic-alfa8)",
      "basic-alfa80": "var(--basic-alfa80)",
      "basic-alfa9": "var(--basic-alfa9)",
      "black-alfa16": "var(--black-alfa16)",
      "black-alfa24": "var(--black-alfa24)",
      "black-alfa32": "var(--black-alfa32)",
      "black-alfa40": "var(--black-alfa40)",
      "black-alfa48": "var(--black-alfa48)",
      "black-alfa8": "var(--black-alfa8)",
      "error-400": "var(--error-400)",
      "error-500": "var(--error-500)",
      "error-600": "var(--error-600)",
      "error-700": "var(--error-700)",
      "error-alfa16": "var(--error-alfa16)",
      "error-alfa24": "var(--error-alfa24)",
      "error-alfa32": "var(--error-alfa32)",
      "error-alfa8": "var(--error-alfa8)",
      "info-400": "var(--info-400)",
      "info-500": "var(--info-500)",
      "info-600": "var(--info-600)",
      "info-700": "var(--info-700)",
      "info-800": "var(--info-800)",
      "info-alfa16": "var(--info-alfa16)",
      "info-alfa24": "var(--info-alfa24)",
      "info-alfa32": "var(--info-alfa32)",
      "info-alfa8": "var(--info-alfa8)",
      "primary-100": "var(--primary-100)",
      "primary-200": "var(--primary-200)",
      "primary-300": "var(--primary-300)",
      "primary-400": "var(--primary-400)",
      "primary-500": "var(--primary-500)",
      "primary-600": "var(--primary-600)",
      "primary-700": "var(--primary-700)",
      "primary-alfa12": "var(--primary-alfa12)",
      "primary-alfa16": "var(--primary-alfa16)",
      "primary-alfa24": "var(--primary-alfa24)",
      "primary-alfa32": "var(--primary-alfa32)",
      "primary-alfa40": "var(--primary-alfa40)",
      "primary-alfa48": "var(--primary-alfa48)",
      "primary-alfa8": "var(--primary-alfa8)",
      "success-400": "var(--success-400)",
      "success-500": "var(--success-500)",
      "success-600": "var(--success-600)",
      "success-700": "var(--success-700)",
      "success-800": "var(--success-800)",
      "success-alfa16": "var(--success-alfa16)",
      "success-alfa24": "var(--success-alfa24)",
      "success-alfa32": "var(--success-alfa32)",
      "success-alfa8": "var(--success-alfa8)",
      "systemoverlay-64": "var(--systemoverlay-64)",
      "systemoverlay-80": "var(--systemoverlay-80)",
      "text-icon-colorsdark": "var(--text-icon-colorsdark)",
      "text-icon-colorsgrey": "var(--text-icon-colorsgrey)",
      "text-icon-colorslight": "var(--text-icon-colorslight)",
      "text-icon-colorslight-grey": "var(--text-icon-colorslight-grey)",
      "warning-400": "var(--warning-400)",
      "warning-500": "var(--warning-500)",
      "warning-600": "var(--warning-600)",
      "warning-700": "var(--warning-700)",
      "warning-alfa16": "var(--warning-alfa16)",
      "warning-alfa24": "var(--warning-alfa24)",
      "warning-alfa32": "var(--warning-alfa32)",
      "warning-alfa8": "var(--warning-alfa8)",
    },
    fontFamily:{
      'twitter-chirp': ['TwitterChirp', 'sans-serif'],
        'twitter-chirp-extended': ['TwitterChirpExtendedHeavy', 'sans-serif'],     
      "body-text-b1-bold": "var(--body-text-b1-bold-font-family)",
      "body-text-b1-medium": "var(--body-text-b1-medium-font-family)",
      "body-text-b1-regular": "var(--body-text-b1-regular-font-family)",
      "body-text-b2-bold": "var(--body-text-b2-bold-font-family)",
      "body-text-b2-medium": "var(--body-text-b2-medium-font-family)",
      "body-text-b2-regular": "var(--body-text-b2-regular-font-family)",
      "body-text-messages": "var(--body-text-messages-font-family)",
      "body-text-messages-name": "var(--body-text-messages-name-font-family)",
      "button-giant": "var(--button-giant-font-family)",
      "button-large": "var(--button-large-font-family)",
      "button-medium": "var(--button-medium-font-family)",
      "button-small": "var(--button-small-font-family)",
      "caption-c1-bold": "var(--caption-c1-bold-font-family)",
      "caption-c1-medium": "var(--caption-c1-medium-font-family)",
      "caption-c1-regular": "var(--caption-c1-regular-font-family)",
      "caption-c2-bold": "var(--caption-c2-bold-font-family)",
      "caption-c2-medium": "var(--caption-c2-medium-font-family)",
      "caption-c2-regular": "var(--caption-c2-regular-font-family)",
      "headline-h1": "var(--headline-h1-font-family)",
      "headline-h2": "var(--headline-h2-font-family)",
      "headline-h3": "var(--headline-h3-font-family)",
      "headline-h4": "var(--headline-h4-font-family)",
      "headline-h5": "var(--headline-h5-font-family)",
      "headline-h6": "var(--headline-h6-font-family)",
      "label-medium": "var(--label-medium-font-family)",
      "label-small": "var(--label-small-font-family)",
      link: "var(--link-font-family)",
      "overline-overline-1-regular": "var(--overline-overline-1-regular-font-family)",
      "overline-overline-2-bold": "var(--overline-overline-2-bold-font-family)",
      "overline-overline-2-medium": "var(--overline-overline-2-medium-font-family)",
      "overline-overline-2-regular": "var(--overline-overline-2-regular-font-family)",
      "paragraph-p1-bold": "var(--paragraph-p1-bold-font-family)",
      "paragraph-p1-medium": "var(--paragraph-p1-medium-font-family)",
      "paragraph-p1-regular": "var(--paragraph-p1-regular-font-family)",
      "paragraph-p2-bold": "var(--paragraph-p2-bold-font-family)",
      "paragraph-p2-medium": "var(--paragraph-p2-medium-font-family)",
      "paragraph-p2-regular": "var(--paragraph-p2-regular-font-family)",
      "placeholder-medium": "var(--placeholder-medium-font-family)",
      "placeholder-small": "var(--placeholder-small-font-family)",
      "placeholder-x-small": "var(--placeholder-x-small-font-family)",
    },
    boxShadow: {
      "1-6dp": "var(--1-6dp)",
      "2-4dp": "var(--2-4dp)",
      "2dp": "var(--2dp)",
      "4-0dp": "var(--4-0dp)",
      "4dp": "var(--4dp)",
      "8dp": "var(--8dp)",
      "focus-state": "var(--focus-state)",
      'subscribe-card-shadow': '0px 44px 50px rgba(112, 109, 129, 0.05)'
    },
    }
  },
  plugins: [
    ({ addVariant }) => {
      addVariant('inner', '& > *');
    },
    require('@tailwindcss/forms')
  ]
};
